### PR TITLE
Fix build error with Makefiles

### PR DESCRIPTION
**Pull request by daleclack**
When I try to use gresource with cmake and Unix Makefiles, I found an error.
The make program compliant about no rules to make resource file, and I change the DEPENDS to fix this error

### CODE REVIEW

**Comment by Makman2** [comment]
Thanks for the PR :smile: 

So I can understand the issue better, could you post the exact error and how you invoked the macros, so I can reproduce it? @daleclack

**Comment by daleclack** [comment]
This is my cmake command for Compile resources, as it sees, I put the resources s file in a custom directory
```
#Compile Resource                               
set(RESOURCE_LIST                             
      gnome-fs-directory.png                          
      gnome-fs-regular.png                            
      icons/24x24/actions/view-grid-symbolic.png      
      icons/24x24/actions/view-list-symbolic.png      
      icons/48x48/actions/dialog-error.png)  

 compile_gresources(RESOURCE_FILE                                   
                                   XML_OUT                                         
                                   TYPE EMBED_C                                    
                                   RESOURCES ${RESOURCE_LIST}                      
                                   PREFIX "/org/gtk/daleclack"                    
                                   SOURCE_DIR ${PROJECT_SOURCE_DIR}/../default_res)
```
And when I try to compile with make, the make thrown a error:
```
make[2]: *** No rule to make target 'icons/48x48/actions/dialog-error.png', needed by '.gresource.xml'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:112: CMakeFiles/gtk113.dir/all] Error 2
make: *** [Makefile:121: all] Error 2
```

**Comment by daleclack** [comment]
This is the change of build.make when I changed the CMake Module:
Before Change:
```
CMakeFiles/resource: resources.c

resources.c: gnome-fs-directory.png
resources.c: gnome-fs-regular.png
resources.c: icons/24x24/actions/view-grid-symbolic.png
resources.c: icons/24x24/actions/view-list-symbolic.png
resources.c: icons/48x48/actions/dialog-error.png
resources.c: .gresource.xml
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/sd/Gtkmm3/gtk113_file_gtkmm/build1/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating resources.c"
	/usr/bin/glib-compile-resources --target /sd/Gtkmm3/gtk113_file_gtkmm/build1/resources.c --sourcedir /sd/Gtkmm3/gtk113_file_gtkmm/../default_res --generate-source /sd/Gtkmm3/gtk113_file_gtkmm/build1/.gresource.xml

.gresource.xml: gnome-fs-directory.png
.gresource.xml: gnome-fs-regular.png
.gresource.xml: icons/24x24/actions/view-grid-symbolic.png
.gresource.xml: icons/24x24/actions/view-list-symbolic.png
.gresource.xml: icons/48x48/actions/dialog-error.png
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/sd/Gtkmm3/gtk113_file_gtkmm/build1/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Creating gresources XML file (.gresource.xml)"
	/usr/bin/cmake -D GXML_OUTPUT="/sd/Gtkmm3/gtk113_file_gtkmm/build1/.gresource.xml" -D GXML_PREFIX="/org/gtk/daleclack" -D GXML_RESOURCES="gnome-fs-directory.png gnome-fs-regular.png icons/24x24/actions/view-grid-symbolic.png icons/24x24/actions/view-list-symbolic.png icons/48x48/actions/dialog-error.png" -P "/sd/GCR_CMake/macros/BuildTargetScript.cmake"
```

After Change:
```
CMakeFiles/resource: resources.c

resources.c: /sd/Gtkmm3/default_res/gnome-fs-directory.png
resources.c: /sd/Gtkmm3/default_res/gnome-fs-regular.png
resources.c: /sd/Gtkmm3/default_res/icons/24x24/actions/view-grid-symbolic.png
resources.c: /sd/Gtkmm3/default_res/icons/24x24/actions/view-list-symbolic.png
resources.c: /sd/Gtkmm3/default_res/icons/48x48/actions/dialog-error.png
resources.c: .gresource.xml
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/sd/Gtkmm3/gtk113_file_gtkmm/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Generating resources.c"
	/usr/bin/glib-compile-resources --target /sd/Gtkmm3/gtk113_file_gtkmm/build/resources.c --sourcedir /sd/Gtkmm3/gtk113_file_gtkmm/../default_res --generate-source /sd/Gtkmm3/gtk113_file_gtkmm/build/.gresource.xml

.gresource.xml: /sd/Gtkmm3/default_res/gnome-fs-directory.png
.gresource.xml: /sd/Gtkmm3/default_res/gnome-fs-regular.png
.gresource.xml: /sd/Gtkmm3/default_res/icons/24x24/actions/view-grid-symbolic.png
.gresource.xml: /sd/Gtkmm3/default_res/icons/24x24/actions/view-list-symbolic.png
.gresource.xml: /sd/Gtkmm3/default_res/icons/48x48/actions/dialog-error.png
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/sd/Gtkmm3/gtk113_file_gtkmm/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Creating gresources XML file (.gresource.xml)"
	/usr/bin/cmake -D GXML_OUTPUT="/sd/Gtkmm3/gtk113_file_gtkmm/build/.gresource.xml" -D GXML_PREFIX="/org/gtk/daleclack" -D GXML_RESOURCES="gnome-fs-directory.png gnome-fs-regular.png icons/24x24/actions/view-grid-symbolic.png icons/24x24/actions/view-list-symbolic.png icons/48x48/actions/dialog-error.png" -P "/sd/GCR_CMake/macros/BuildTargetScript.cmake"
```

I think the problem is that the "make" command thinks the resources files is needed to be generated because it can't find the file with only a file name
(My native language is not English)

**Comment by daleclack** [comment]
The original code can be found here:
https://www.github.com/daleclack/testing-repository/tree/master/Gtkmm3%2Fgtk113_file_gtkmm

**Comment by Makman2** [comment]
@daleclack I formatted your comments so it's easier to read the actual code.

I will check up on this, thanks for the details :)

**Comment by Makman2** [comment]
Thank you for the fix, I am actually wrongfully ignoring `SOURCE_DIR` on the input resource list.

To do some quick cosmetic changes, I moved this one to https://github.com/Makman2/GCR_CMake/pull/21.

Thanks again for the submission :D Will soon draft a new release.

**Comment by Makman2** [comment]
Release v3.5 out: https://github.com/Makman2/GCR_CMake/releases/tag/3.5

**Comment by daleclack** [comment]
> @daleclack I formatted your comments so it's easier to read the actual code.
> 
> I will check up on this, thanks for the deta


I think it may be a bug of github on Android, however, the issue has been fixed, and thanks for checking the code and issue :)

**Pull request closed without merging**
